// AUTO-GENERATED by scripts/import-expenses.mjs — do not edit
export const IMPORTED_TX = [
  {
    "id": "cfbead96f46b",
    "date": "2026-04-01",
    "amount": 540,
    "categoryId": "shopping",
    "note": "Tshirts",
    "person": "Selva"
  },
  {
    "id": "f794f7d92819",
    "date": "2026-04-01",
    "amount": 2000,
    "categoryId": "parents",
    "note": "Kuttalam Pidari Kumbabhishekam",
    "person": "Selva"
  },
  {
    "id": "852bcd3986d3",
    "date": "2026-04-01",
    "amount": 20000,
    "categoryId": "parents",
    "note": "Appa - 10000",
    "person": "Selva"
  },
  {
    "id": "990607d9269b",
    "date": "2026-04-01",
    "amount": 66500,
    "categoryId": "rent",
    "note": "Rent + Maintenance",
    "person": "Selva"
  },
  {
    "id": "146ab2e62c09",
    "date": "2026-04-01",
    "amount": 678,
    "categoryId": "utilities",
    "note": "ACT Bill",
    "person": "Selva"
  },
  {
    "id": "2e62cd46bc83",
    "date": "2026-04-03",
    "amount": 871,
    "categoryId": "food",
    "note": "Desert",
    "person": "Selva"
  },
  {
    "id": "38758dcc1b27",
    "date": "2026-04-03",
    "amount": 176,
    "categoryId": "grocery",
    "note": "Grocery",
    "person": "Selva"
  },
  {
    "id": "264eeeaf7511",
    "date": "2026-04-04",
    "amount": 5000,
    "categoryId": "parents",
    "note": "Thaila Donation",
    "person": "Selva"
  },
  {
    "id": "eda080a9ea50",
    "date": "2026-04-04",
    "amount": 550,
    "categoryId": "food",
    "note": "Burrito",
    "person": "Selva"
  },
  {
    "id": "f2badba361c8",
    "date": "2026-04-05",
    "amount": 1122,
    "categoryId": "baby",
    "note": "Baby Clothes",
    "person": "Selva"
  },
  {
    "id": "61a7ed30cf44",
    "date": "2026-04-05",
    "amount": 190,
    "categoryId": "grocery",
    "note": "Juice",
    "person": "Selva"
  },
  {
    "id": "92b254da2ad4",
    "date": "2026-04-05",
    "amount": 627,
    "categoryId": "grocery",
    "note": "Protein",
    "person": "Selva"
  },
  {
    "id": "051943c81fe5",
    "date": "2026-04-06",
    "amount": 894,
    "categoryId": "baby",
    "note": "First Cry Membership",
    "person": "Selva"
  },
  {
    "id": "0ec4a9ae33f0",
    "date": "2026-04-06",
    "amount": 457,
    "categoryId": "baby",
    "note": "Baby diapers",
    "person": "Selva"
  },
  {
    "id": "116104751a90",
    "date": "2026-04-07",
    "amount": 1144,
    "categoryId": "baby",
    "note": "Diapers for Baby",
    "person": "Selva"
  },
  {
    "id": "f5afc9e22822",
    "date": "2026-04-07",
    "amount": 319,
    "categoryId": "food",
    "note": "Swiggy Sweets",
    "person": "Selva"
  },
  {
    "id": "52f260bad60c",
    "date": "2026-04-09",
    "amount": 334,
    "categoryId": "medical",
    "note": "Drops for Ladoo + Doctor Consultation",
    "person": "Selva"
  },
  {
    "id": "808d1c433293",
    "date": "2026-04-10",
    "amount": 2900,
    "categoryId": "weekend_fun",
    "note": "Outing to Aquarium",
    "person": "Selva"
  },
  {
    "id": "90cc979daff3",
    "date": "2026-04-10",
    "amount": 1075,
    "categoryId": "food",
    "note": "Food Order for Dinner",
    "person": "Selva"
  },
  {
    "id": "f12c1bcb6e7e",
    "date": "2026-04-11",
    "amount": 340,
    "categoryId": "food",
    "note": "Icecream with Archana",
    "person": "Selva"
  },
  {
    "id": "6f7a907bf748",
    "date": "2026-04-12",
    "amount": 846,
    "categoryId": "food",
    "note": "Nakshatra Dinner",
    "person": "Selva"
  },
  {
    "id": "10e0d8d0e52f",
    "date": "2026-04-12",
    "amount": 173,
    "categoryId": "baby",
    "note": "Baby Band",
    "person": "Selva"
  },
  {
    "id": "92872b223148",
    "date": "2026-04-12",
    "amount": 353,
    "categoryId": "utilities",
    "note": "Postpaid Bill",
    "person": "Selva"
  },
  {
    "id": "2218e39b6c3c",
    "date": "2026-04-13",
    "amount": 609,
    "categoryId": "baby",
    "note": "Wipes + Body Wash",
    "person": "Selva"
  },
  {
    "id": "ae2dc188a7ad",
    "date": "2026-04-14",
    "amount": 1580,
    "categoryId": "baby",
    "note": "Skillmatics Peekaboo Book",
    "person": "Selva"
  },
  {
    "id": "cfab6edcaa54",
    "date": "2026-04-14",
    "amount": 690,
    "categoryId": "grocery",
    "note": "Grocery",
    "person": "Selva"
  },
  {
    "id": "e4bd98ced959",
    "date": "2026-04-15",
    "amount": 300,
    "categoryId": "utilities",
    "note": "Water Filter",
    "person": "Selva"
  },
  {
    "id": "281416d787e2",
    "date": "2026-04-15",
    "amount": 674,
    "categoryId": "baby",
    "note": "Playmat",
    "person": "Selva"
  },
  {
    "id": "1c9c3f7d9891",
    "date": "2026-04-16",
    "amount": 3000,
    "categoryId": "gifts",
    "note": "Shreyas Anna Gift",
    "person": "Selva"
  },
  {
    "id": "6b91ec777845",
    "date": "2026-04-16",
    "amount": 822,
    "categoryId": "weekend_fun",
    "note": "Lunch at CBE + Movie",
    "person": "Selva"
  },
  {
    "id": "8d0141dcd473",
    "date": "2026-04-16",
    "amount": 1800,
    "categoryId": "transport",
    "note": "Ticket to CBE",
    "person": "Selva"
  },
  {
    "id": "00e568855992",
    "date": "2026-04-17",
    "amount": 4700,
    "categoryId": "non_recurring",
    "note": "Advance for Vandana Teyjesh",
    "person": "Selva"
  },
  {
    "id": "7871a0ad4617",
    "date": "2026-04-17",
    "amount": 800,
    "categoryId": "transport",
    "note": "Auto + Cab Charges",
    "person": "Selva"
  },
  {
    "id": "480893a4c70b",
    "date": "2026-04-18",
    "amount": 2781,
    "categoryId": "medical",
    "note": "Medicines for Akshaya + Finax",
    "person": "Selva"
  },
  {
    "id": "d5b6833a81e2",
    "date": "2026-04-18",
    "amount": 1356,
    "categoryId": "baby",
    "note": "Diapers for Ladoo",
    "person": "Selva"
  },
  {
    "id": "1a11529f0738",
    "date": "2026-04-20",
    "amount": 1378,
    "categoryId": "grocery",
    "note": "Whey",
    "person": "Selva"
  },
  {
    "id": "5a9ea6e014f8",
    "date": "2026-04-25",
    "amount": 1000,
    "categoryId": "transport",
    "note": "Ticket to Madurai",
    "person": "Selva"
  },
  {
    "id": "c6c818679d5f",
    "date": "2026-04-26",
    "amount": 818,
    "categoryId": "transport",
    "note": "Train to Bangalore",
    "person": "Selva"
  },
  {
    "id": "1bde40472a4a",
    "date": "2026-04-26",
    "amount": 1900,
    "categoryId": "gifts",
    "note": "Harish Baby Shower Gift",
    "person": "Selva"
  },
  {
    "id": "03b8f123d8d1",
    "date": "2026-04-28",
    "amount": 730,
    "categoryId": "transport",
    "note": "Train to Chennai",
    "person": "Selva"
  }
];
